# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
                ('releaseYear', models.CharField(max_length=10)),
                ('production', models.CharField(max_length=100)),
                ('storyline', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=30)),
                ('duration', models.BigIntegerField(default=0)),
                ('movieURL', models.CharField(max_length=1000)),
                ('woodType', models.CharField(max_length=20)),
                ('views', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('dislikes', models.BigIntegerField(default=0)),
            ],
        ),
    ]
