# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imageURL',
            field=models.CharField(default='http://www.mvies.com', max_length=1000),
        ),
    ]
